# Generated by Django 5.1.4 on 2024-12-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_market', '0022_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
